import * as React from 'react';
import { styled } from '@mui/material/styles';
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Head from 'next/head';
import Sidebar from './Sidebar/Sidebar';
import TopBar from './TopBar';
import MainSection from './MainSection';


const Item = styled(Paper)(({ theme }) => ({
  backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
  ...theme.typography.body2,
  textAlign: 'center',
  color: theme.palette.text.secondary,
}));

export default function Layout({children}) {
  return (
    <div>
      <Head>
        <title>Next DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ flexGrow: 1 }}>
        <Grid container spacing={1}>
          <Grid item xs>
            <Item>
              <Sidebar />
            </Item>
          </Grid>
          <Grid item xs={9}>
            <Item>
              <main>
                <TopBar />
                <MainSection >
                  {children}
                </MainSection>
              </main>
            </Item>
          </Grid>
        </Grid>
      </Box>
    </div>
  )
}
